<a href="https://colab.research.google.com/github/pratigya0/devops-exercises/blob/main/scalar_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
python_list = [1, 5, 3, 6, -8]
python_list


[1, 5, 3, 6, -8]

In [ ]:
numpy_arr = np.array(python_list)
len(numpy_arr.shape)

1

In [ ]:
python_list_list = [[1,2],[3,4]]
python_list_list

[[1, 2], [3, 4]]

In [ ]:
np.array(python_list_list)


array([[1, 2],
       [3, 4]])

In [ ]:
numpy_arr2 = np.array(python_list_list)
numpy_arr2.shape

(2, 2)

In [ ]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.random.randint(5, size =(2,2) )

array([[4, 1],
       [2, 2]])

In [ ]:
#checking datatype
import numpy as np
a = [1, 2, 3, 4, 5, 6, 45]
arr = np.array(a)
arr.dtype

dtype('int64')